export const techProductWithBrands = {
  laptops: ["dell", "hp", "apple", "lenovo", "asus", "acer", "msi", "razer"],
  desktops: [
    "dell",
    "hp",
    "lenovo",
    "apple",
    "asus",
    "acer",
    "cyberpowerpc",
    "ibuypower",
  ],
  smartphones: [
    "apple",
    "samsung",
    "google",
    "oneplus",
    "xiaomi",
    "huawei",
    "oppo",
    "vivo",
  ],
  tablets: ["apple", "samsung", "microsoft", "lenovo", "huawei", "amazon"],
  monitors: ["dell", "samsung", "lg", "asus", "acer", "benq", "hp", "msi"],
  "printers & scanners": [
    "hp",
    "canon",
    "epson",
    "brother",
    "xerox",
    "lexmark",
  ],
  "networking equipment": [
    "netgear",
    "tp-link",
    "cisco",
    "asus",
    "linksys",
    "ubiquiti",
    "d-link",
  ],
  "storage devices": [
    "western digital",
    "seagate",
    "sandisk",
    "kingston",
    "samsung",
    "crucial",
    "toshiba",
  ],
  "pc components": [
    "intel",
    "amd",
    "nvidia",
    "corsair",
    "msi",
    "asus",
    "gigabyte",
    "evga",
  ],
  "wearable devices": [
    "apple",
    "fitbit",
    "samsung",
    "garmin",
    "xiaomi",
    "huawei",
  ],
  "smart home devices": [
    "google",
    "amazon",
    "apple",
    "philips hue",
    "ring",
    "nest",
    "tp-link",
  ],
  "gaming consoles": ["sony", "microsoft", "nintendo", "steam", "XBox"],
  "audio equipment": [
    "bose",
    "sony",
    "jbl",
    "sennheiser",
    "beats",
    "logitech",
    "audio-technica",
  ],
  "camera & photography": [
    "canon",
    "nikon",
    "sony",
    "fujifilm",
    "olympus",
    "gopro",
    "dahua",
  ],
  drones: ["dji", "autel robotics", "parrot", "skydio", "holy stone"],
  "vr system": ["meta", "apple", "pico", "playstation"],
  "software & subscriptions": [
    "microsoft",
    "adobe",
    "apple",
    "google",
    "autodesk",
    "zoom",
  ],
  "charging accessories": [
    "anker",
    "belkin",
    "apple",
    "samsung",
    "ravpower",
    "mophie",
  ],
  "keyboards & mice": [
    "logitech",
    "razer",
    "corsair",
    "steelseries",
    "microsoft",
    "apple",
    "asus",
  ],
  "graphics tablets": ["wacom", "huion", "xp-pen", "gaomon", "ugee"],
  projectors: ["epson", "benq", "optoma", "viewsonic", "lg", "sony"],
  "power supplies & ups": [
    "apc",
    "cyberpower",
    "evga",
    "corsair",
    "seasonic",
    "cooler master",
  ],
};
