export const techProductWithBrands = {
  Laptops: ["Dell", "HP", "Apple", "Lenovo", "ASUS", "Acer", "MSI", "Razer"],
  Desktops: [
    "Dell",
    "HP",
    "Lenovo",
    "Apple",
    "ASUS",
    "Acer",
    "CyberPowerPC",
    "iBUYPOWER",
  ],
  Smartphones: [
    "Apple",
    "Samsung",
    "Google",
    "OnePlus",
    "Xiaomi",
    "Huawei",
    "Oppo",
    "Vivo",
  ],
  Tablets: ["Apple", "Samsung", "Microsoft", "Lenovo", "Huawei", "Amazon"],
  Monitors: ["Dell", "Samsung", "LG", "ASUS", "Acer", "BenQ", "HP", "MSI"],
  "Printers & Scanners": [
    "HP",
    "Canon",
    "Epson",
    "Brother",
    "Xerox",
    "Lexmark",
  ],
  "Networking Equipment": [
    "Netgear",
    "TP-Link",
    "Cisco",
    "Asus",
    "Linksys",
    "Ubiquiti",
    "D-Link",
  ],
  "Storage Devices": [
    "Western Digital",
    "Seagate",
    "SanDisk",
    "Kingston",
    "Samsung",
    "Crucial",
    "Toshiba",
  ],
  "PC Components": [
    "Intel",
    "AMD",
    "NVIDIA",
    "Corsair",
    "MSI",
    "ASUS",
    "Gigabyte",
    "EVGA",
  ],
  "Wearable Devices": [
    "Apple",
    "Fitbit",
    "Samsung",
    "Garmin",
    "Xiaomi",
    "Huawei",
  ],
  "Smart Home Devices": [
    "Google",
    "Amazon",
    "Apple",
    "Philips Hue",
    "Ring",
    "Nest",
    "TP-Link",
  ],
  "Gaming Consoles": ["Sony", "Microsoft", "Nintendo", "Steam"],
  "Audio Equipment": [
    "Bose",
    "Sony",
    "JBL",
    "Sennheiser",
    "Beats",
    "Logitech",
    "Audio-Technica",
  ],
  "Camera & Photography": [
    "Canon",
    "Nikon",
    "Sony",
    "Fujifilm",
    "Olympus",
    "GoPro",
  ],
  Drones: ["DJI", "Autel Robotics", "Parrot", "Skydio", "Holy Stone"],
  "VR & AR Devices": ["Meta", "Sony", "HTC", "Valve", "Microsoft", "Pico"],
  "Software & Subscriptions": [
    "Microsoft",
    "Adobe",
    "Apple",
    "Google",
    "Autodesk",
    "Zoom",
  ],
  "Charging Accessories": [
    "Anker",
    "Belkin",
    "Apple",
    "Samsung",
    "RAVPower",
    "Mophie",
  ],
  "Keyboards & Mice": [
    "Logitech",
    "Razer",
    "Corsair",
    "SteelSeries",
    "Microsoft",
    "Apple",
  ],
  "Graphics Tablets": ["Wacom", "Huion", "XP-Pen", "Gaomon", "UGEE"],
  Projectors: ["Epson", "BenQ", "Optoma", "ViewSonic", "LG", "Sony"],
  "Power Supplies & UPS": [
    "APC",
    "CyberPower",
    "EVGA",
    "Corsair",
    "Seasonic",
    "Cooler Master",
  ],
};
